services:
  - type: web
    name: chat-backend
    env: docker
    autoDeploy: true
    plan: starter
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
